project_id = "xazlrdwdkafhzwkezfxz"

[functions]
import_map = "./functions/import_map.json"

[functions.process-email-queue]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true

[functions.webauthn-challenge]
verify_jwt = true

[functions.webauthn-verify]
verify_jwt = true

[functions.generate-renewal-charge]
verify_jwt = true

[functions.send-invite-email]
verify_jwt = true