project_id = "xazlrdwdkafhzwkezfxz"

[functions]
import_map = "./functions/import_map.json"

[functions.process-email-queue]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true